name: Deploy master branch

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  # pylint:
  #   name: Code Analysis with Pylint
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.8", "3.9", "3.10"]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install pylint
  #   - name: Analyse code with Pylint
  #     run: |
  #       pylint $(git ls-files '*.py')

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Serverless Deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
        role-to-assume: arn:aws:iam::060795936663:role/aws_access
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
       